# -*- coding: utf-8 -*-
"""0709

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FG6WBOgUlck_4Y44hf6T-i-geSG5FHH4
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("breast_cancer_diagnostic_data (1).csv")
plt.scatter(data["area_mean"],data["texture_worst"])
plt.ylabel("Texture")
plt.xlabel("area of the cancer")
plt.title("Breast Cancer Diagnoses")
plt.show()
print(data)

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("breast_cancer_diagnostic_data (1).csv")
fig,axes = plt.subplots(2,2)
axes[0][0].scatter(data["smoothness_mean"],data["texture_mean"])
axes[0][0].set_xlabel("smoothness")
axes[0][0].set_ylabel("texture mean")



axes[0][1].scatter(data["compactness_mean"],data["texture_mean"])
axes[0][1].set_xlabel("compactness")
axes[0][1].set_ylabel("texture mean")


axes[1][0].scatter(data["concavity_mean"],data["texture_mean"])
axes[1][0].set_ylabel("texture mean")
axes[1][0].set_xlabel("concavity")

axes[1][1].scatter(data["concave points_mean"],data["texture_mean"])
axes[1][1].set_ylabel("texture mean")
axes[1][1].set_xlabel("concave points")
fig.subplots_adjust(hspace=1, wspace = 1)
plt.savefig("BCDS(Breast Cancer Data Science)", dpi = 500)
plt.show()

import seaborn as sns

corr_matrix = data.drop(columns=["id","diagnosis"]).corr()

sns.heatmap(corr_matrix, cmap = "coolwarm")

plt.show()

data = pd.read_csv("breast_cancer_diagnostic_data (1).csv")

pivot_table = data.groupby('diagnosis').mean()
sns.boxplot(x="diagnosis",y="symmetry_worst",data=data)
plt.savefig("HUh",dpi=500)

data = pd.read_csv("breast_cancer_diagnostic_data (1).csv")

pivot_table = data.groupby('diagnosis').mean()
sns.boxplot(x="diagnosis",y="radius_mean",data=data)
plt.show()